# Generated by Django 3.2.8 on 2021-10-26 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='films',
            new_name='film',
        ),
    ]
